include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    prefer_asserts_with_message: ignore
    lines_longer_than_80_chars: ignore
    sort_constructors_first: ignore
  exclude:
    - "/*.g.dart"
    - "*.g.dart"
    - "/*.gen.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"

linter:
  rules:
    public_member_api_docs: false
