name: product_catalog_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.2.2
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  easy_localization: ^3.0.7
  envied: ^1.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  mockito: ^5.4.5

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  envied_generator: ^1.0.0
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.0
  json_serializable: ^6.9.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/translations/
    - assets/images/
  #   - images/a_dot_ham.jpeg
